# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../choose_property.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from create_dialog import Connection


class CustomChooseDialog(QtWidgets.QDialog):
    choiceDoneSignal = QtCore.pyqtSignal(Connection)


class UiChooseDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(430, 140)
        Dialog.setMinimumSize(QtCore.QSize(430, 140))
        Dialog.setMaximumSize(QtCore.QSize(430, 140))
        Dialog.setStyleSheet("background-color: rgb(232, 248, 255);")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setMinimumSize(QtCore.QSize(100, 0))
        self.okButton.setStyleSheet("background-color: rgb(175, 226, 255);")
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.objectPropertyRadioButton = QtWidgets.QRadioButton(Dialog)
        self.objectPropertyRadioButton.setObjectName("objectPropertyRadioButton")
        self.gridLayout.addWidget(self.objectPropertyRadioButton, 0, 0, 1, 2)
        self.dataPropertyRadioButton = QtWidgets.QRadioButton(Dialog)
        self.dataPropertyRadioButton.setObjectName("dataPropertyRadioButton")
        self.gridLayout.addWidget(self.dataPropertyRadioButton, 2, 0, 1, 2)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.okButton.setEnabled(False)
        self.okButton.clicked.connect(lambda: self.handle_ok(Dialog))
        self.objectPropertyRadioButton.clicked.connect(self.handle_radio_button)
        self.dataPropertyRadioButton.clicked.connect(self.handle_radio_button)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def handle_radio_button(self):
        if self.objectPropertyRadioButton.isChecked() or self.dataPropertyRadioButton.isChecked():
            self.okButton.setEnabled(True)
        else:
            self.okButton.setEnabled(False)

    def handle_ok(self, Dialog):
        if self.objectPropertyRadioButton.isChecked():
            Dialog.choiceDoneSignal.emit(Connection.PROVIDE_OBJECT_PROPERTY)
        elif self.dataPropertyRadioButton.isChecked():
            Dialog.choiceDoneSignal.emit(Connection.PROVIDE_DATA_PROPERTY)
        Dialog.accept()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Provide property"))
        self.okButton.setText(_translate("Dialog", "Ok"))
        self.objectPropertyRadioButton.setText(_translate("Dialog", "Provide object property"))
        self.dataPropertyRadioButton.setText(_translate("Dialog", "Provide data property"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = CustomChooseDialog()
    ui = UiChooseDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
